"""add buyer_pan_number and vendor_address to invoices

Revision ID: 153eb545933c
Revises: be5b75e1a7fe
Create Date: 2026-04-28 15:03:37.953234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '153eb545933c'
down_revision: Union[str, Sequence[str], None] = 'be5b75e1a7fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('buyer_pan_number', sa.String(length=15), nullable=True))
    op.add_column('invoices', sa.Column('vendor_address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'vendor_address')
    op.drop_column('invoices', 'buyer_pan_number')
    # ### end Alembic commands ###
