"""add domain to companies, per-tenant oauth

Revision ID: be5b75e1a7fe
Revises: 13430cf62eca
Create Date: 2026-04-14 12:03:39.560426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be5b75e1a7fe'
down_revision: Union[str, Sequence[str], None] = '13430cf62eca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('domain', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_companies_domain'), 'companies', ['domain'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_domain'), table_name='companies')
    op.drop_column('companies', 'domain')
    # ### end Alembic commands ###
